server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/StudentClub
    username: root
    password: QIxuCHen8523622
    driver-class-name: com.mysql.cj.jdbc.Driver

    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
#
#  mybatis:
#    mapperLocations: classpath:mapper/*.xml
#    config-location: classpath:mybatis-config.xml
#    typeAliasesPackage: com.example.domain

aliyun:
  oss:
    access-id: LTAI4G1vT51hqgFohKJ4rJ6t
    access-key: zIOoNFLwKBEXp1gEQOLolGnpByOTpH
    bucket: jooc-studentclub
    endpoint: oss-cn-huhehaote.aliyuncs.com
    dir: studentclub
    expire:
