server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mcalendar
    username: root
    password: QIxuCHen8523622
    driver-class-name: com.mysql.cj.jdbc.Driver

    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5