# Uncomment the next line to define a global platform for your project

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '13.2'

target 'StudentClub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudentClub
  pod 'Alamofire', '~> 5.0'
  pod 'Kingfisher/SwiftUI', '~> 5.13.0'

end
